[package]
name = "dcs_no_joystick_type_beat"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "2.1.0"
mouse-rs = "=0.4.2"
display-info = "0.5.1"
vjoy = "0.6.0"
shared_memory = "0.12.4"
bytemuck = { version = "1.16.0", features = ["derive"] }
libloading = "0.8.3"